### ISSUE TITLE
Dataset information

### ISSUE THREAD

**Issue by VGrondin** [csiro-robotics/Wild-Places#2]
Hi, great paper! I was wondering if images were recorded in sync with the point cloud? 
Thanks

**Comment by peymmo** [comment]
Yes. Images are synchronised but not yet a part of this dataset. Watch this space for new information.

**Comment by shenyanqing1105** [comment]
> Yes. Images are synchronised but not yet a part of this dataset. Watch this space for new information.

Hi, I wonder if the images will be open? Thanks!

**Comment by peymmo** [comment]
Please check the new dataset page for images, Semantics and lidar point clouds. Coming soon. https://csiro-robotics.github.io/WildScenes/
