### ISSUE TITLE
How to generate the is_revisit_.json for the LoGG3D evaluation?

### ISSUE THREAD

**Issue by uljad** [csiro-robotics/Wild-Places#4]
Thank you for your great work. What is the best way to generate the is_revisit json in case I want to evaluate the model using the Karawatha checkpoint and the respective data?

**Comment by kavisha725** [comment]
You do not need the is_revisit json file to evaluate on the Wild-Places dataset. 
Please follow the instructions in:
- Sec [3.2](https://github.com/csiro-robotics/Wild-Places#32-generating-training--testing-splits): to generate test splits.
- Extract and save LoGG3D descriptors for the above splits. 
- Sec [3.3](https://github.com/csiro-robotics/Wild-Places#33-evaluation) to run the evaluation.

**Comment by uljadberdica1000** [comment]
Thank for your reply. Is there a dataset class for karawatha or should I keep on implementing my own?

**Comment by kavisha725** [comment]
I will add the dataloader needed for step 2 above in a few weeks.

**Comment by uljad** [comment]
thank you. I am also trying to write one for the Karawatha  based on the MulranDataset and the PointCould Inheritance. The existing dataloaders use .bin files that have the range information whereas the Wild Places dataset so far doesn't.

**Comment by kavisha725** [comment]
I've added some utils for the dataloader.
See [here](https://github.com/csiro-robotics/Wild-Places/blob/70ffff3b7bf8497fdc627660050f983df15c3871/scripts/eval/logg3d/logg3d_utils.py#L77) for an example on how to add the dataloader for LoGG3D.
