### ISSUE TITLE
No "WebDAV" option for dataset downlaod

### ISSUE THREAD

**Issue by cigdemkknz** [csiro-robotics/Wild-Places#8]
Hello,

Thank you for the excellent work. When I am trying to download the dataset per the instructions, there is no "WebDAV" option in the dropdown menu for the download. I have tried multiple browsers. Any guidance on this will be appreciated!
![image_6487327](https://github.com/csiro-robotics/Wild-Places/assets/128761797/99972d76-9302-4409-9b3b-2fcf1dfbc020)

**Comment by peymmo** [comment]
@JBKnights please help here

**Comment by peymmo** [comment]
@cigdemkknz  Have you been able to download the dataset. We are not able replicate the problem.

**Comment by cigdemkknz** [comment]
Hello,

Thank you very much. I was able to download it.

Kind regards,
Cigdem
